# Single config consumed by scripts/run_remote_experimets.py
# Usage:
#   poetry run python scripts/run_remote_experimets.py remote_run_config.yaml

# --------------------------------------------------
# General config for remote experiment execution
# --------------------------------------------------
experiment_config_module: scaling_llms.experiment_configs.remote_smoke

# Local workspace used to mirror and run training locally
local_project_root: /Users/vasilis/Desktop/workspace/scaling-llms

# Remote GDrive project registry location
remote_project_subdir: ml-experiments/scaling-llms-dev
remote_name: gdrive # Name of the remote configured in rclone config file

# rclone command settings
rclone_executable: rclone
rclone_extra_args: []

# If true, overwrite local run entries when same run identity exists locally
overwrite_runs: false

# --------------------------------------------------
# Runpod config for remote execution
# --------------------------------------------------
image_name: runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
gpu_type_id: NVIDIA A100-SXM4-80GB
cloud_type: SECURE

container_disk_in_gb: 20
volume_in_gb: 40
ports: "22/tcp,8888/http"

identity_file: ~/.ssh/runpod_key

env: {}