experiment_config_module: scaling_llms.experiment_configs.tests.local_runs
cleanup_after_sync: false   # delete local artifacts after each run syncs

registries:
  database_url_env_name: DATABASE_URL
  runs:
    artifacts_root: /workspace/artifacts/runs
    table_name: dev_runs
    sync_hooks_type: rclone
    sync_hooks_args: 
      remote_rclone_name: r2
      remote_artifacts_root: scaling-llms/dev/runs
      global_args: ["--s3-no-check-bucket"]

  datasets:
    artifacts_root: /workspace/artifacts/datasets
    table_name: dev_datasets
    sync_hooks_type: rclone
    sync_hooks_args:
      remote_rclone_name: r2
      remote_artifacts_root: scaling-llms/dev/datasets
      global_args: ["--s3-no-check-bucket"]