# --- Pod Orchestrator Config ---
pod_spec:
  name: test-custom-image
  image_name: stylianouvasilis/scaling-llms:dev-1
  gpu_type_id: # NVIDIA A100-SXM4-80GB
  gpu_count: 0
  cpu_type_id: cpu5g-4-16
  container_disk_in_gb: 40
  volume_in_gb: 40
  env:
    DATABASE_URL: ${DATABASE_URL}
    RUNPOD_PUBLIC_KEY: ${RUNPOD_PUBLIC_KEY}
    RCLONE_CONF_B64: ${RCLONE_CONF_B64}

workflow:
  timeout_s: 600
  poll_s: 5
  terminate_on_failure: false
  retry_policy:
    max_attempts: 5
    retry_base_s: 2.0

# --- Runtime Configs ---
experiment_config: /workspace/runtime_configs/experiment_configs.py
cleanup_after_sync: false   # delete local artifacts after each run syncs

registries:
  database_url_env_name: DATABASE_URL
  runs:
    artifacts_root: /workspace/artifacts/dev/runs
    table_name: dev_runs
    sync_hooks_type: rclone
    sync_hooks_args: 
      remote_rclone_name: r2
      remote_artifacts_root: scaling-llms/dev/runs
      global_args: ["--s3-no-check-bucket"]

  datasets:
    artifacts_root: /workspace/artifacts/dev/datasets
    table_name: dev_datasets
    sync_hooks_type: rclone
    sync_hooks_args:
      remote_rclone_name: r2
      remote_artifacts_root: scaling-llms/dev/datasets
      global_args: ["--s3-no-check-bucket"]